[Service]
Environment=QT_QPA_PLATFORM=ubuntumirclient
Environment=QT_FILE_SELECTORS=ubuntu-touch
Environment=QMLSCENE_DEVICE=haliumqsgcontext
Environment=XDG_RUNTIME_DIR=/run/user/32011
Environment=MIR_SOCKET=/run/user/32011/mir_socket_trusted
Environment=MIR_SERVER_HOST_SOCKET=/run/mir_socket
Environment=MIR_SERVER_NAME=session-0
